#!/bin/ksh
CC=cc \
CXX=CC \
CFLAGS="-march=i686 -O2" \
CXXFLAGS="$CFLAGS" \
./configure --prefix=/usr --disable-nls --disable-shared --disable-rpath --without-iconv

sed -i 's|#define HAVE_ICONV 1||g' config.h
sed -i 's|#define HAVE_LIBINTL_H 1||g' config.h
sed -i 's|"/usr/etc"|"./"|g' config.h
