#
# from makefile.linux26 for Popcorn hour A-100, A-110, B-110
#

PATH:=/usr/local/mips/bin:$(PATH)
export PATH

# Linux 2.6 MIPS OSS NoFPU
OS=lnx26
CC=mipsel-linux-uclibc-gcc
CXX=mipsel-linux-uclibc-g++
CPP=mipsel-linux-uclibc-cpp
RANLIB=mipsel-linux-uclibc-ranlib
AR=mipsel-linux-uclibc-ar
TAR=tar
SED=sed
SHELL=/bin/bash
PATCH=patch
CFLAGS=-DRENICE -DDAEMONIZE -DNO_FPU -Wall -O2 -march=mips32r2 -msoft-float
LDFLAGS=-s

INCLUDE=-Ilib/getopt -Ilib/portaudio/pa_common -Ilib/portaudio/pablio -Ilib/portmixer/px_common -Isrc -Ilib/libmad/$(OS)/include -Ilib/vorbis/$(OS)/include -Ilib/flac/$(OS)/include

PORTAUDIOFILES:=lib/portaudio/pa_unix_oss/pa_unix.c lib/portaudio/pa_unix_oss/pa_unix_oss.c  lib/portaudio/pa_common/pa_lib.c lib/portaudio/pa_common/pa_convert.c lib/portaudio/pablio/ringbuffer.c

LIBMAD=libmad-0.15.1b
LIBOGG=libogg-1.2.2
LIBVORBIS=tremor-r18153
LIBFLAC=flac-1.2.1

PORTMIXERFILES:=lib/portmixer/px_unix_oss/px_unix_oss.c

GETOPTFILES=lib/getopt/getopt.c lib/getopt/getopt1.c

SLIMPROTOFILES:=src/slimaudio/slimaudio_http.c src/slimaudio/slimaudio_decoder.c src/slimaudio/slimaudio_decoder_flac.c src/slimaudio/slimaudio_decoder_mad.c src/slimaudio/slimaudio_decoder_vorbis.c src/slimaudio/slimaudio_decoder_pcm.c src/slimaudio/slimaudio_output.c src/slimaudio/slimaudio_buffer.c src/slimaudio/slimaudio.c src/slimproto/slimproto.c

SQUEEZESLAVEFILES:=src/squeezeslave/squeezeslave.c src/squeezeslave/help.c src/squeezeslave/daemonize.c src/squeezeslave/interactive.c

LIBPORTAUDIO=lib/libportaudio.a

LIBSLIMPROTO=lib/libslimproto.a

LIBGETOPT=lib/libgetopt.a

SUPPORTLIBS=lib/libmad/$(OS)/lib/libmad.a lib/vorbis/$(OS)/lib/libvorbisidec.a lib/vorbis/$(OS)/lib/libogg.a lib/flac/$(OS)/lib/libFLAC.a

SQUEEZESLAVE=bin/squeezeslave

.c.o:
	$(CC) $(CFLAGS) -c $(INCLUDE) $< -o $*.o

all: $(SUPPORTLIBS) $(SQUEEZESLAVE)

lib/libmad/$(OS)/lib/libmad.a:
	cd lib/libmad/$(OS)/build && ${TAR} --bzip -xf ../../../../sources/$(LIBMAD).tar.bz2
	cd lib/libmad/$(OS)/build && ${PATCH} -p0 -i ../../../../patches/libmad-forcemem.patch
	cd lib/libmad/$(OS)/build/$(LIBMAD) && CC="$(CC)" CXXCPP="$(CPP)" CFLAGS="$(CFLAGS)" CPPFLAGS="$(CFLAGS)" LDFLAGS="$(LDFLAGS)" ./configure --enable-shared=no --enable-fpm=mips --host=i686-pc-linux-gnu --build=mipsel-linux-uclibc --target=mipsel-linux-uclibc
	cd lib/libmad/$(OS)/build/$(LIBMAD) && make clean && make
	cp -p lib/libmad/$(OS)/build/$(LIBMAD)/.libs/libmad.a lib/libmad/$(OS)/lib
	cp -p lib/libmad/$(OS)/build/$(LIBMAD)/mad.h lib/libmad/$(OS)/include

lib/vorbis/$(OS)/lib/libogg.a:
	cd lib/vorbis/$(OS)/build && ${TAR} --bzip -xf ../../../../sources/$(LIBOGG).tar.bz2
	cd lib/vorbis/$(OS)/build/$(LIBOGG) && CC="$(CC)" CXXCPP="$(CPP)" CFLAGS="$(CFLAGS)" CPPFLAGS="$(CFLAGS)" LDFLAGS="$(LDFLAGS)" ./configure --enable-shared=no --host=i686-pc-linux-gnu --build=mipsel-linux-uclibc --target=mipsel-linux-uclibc
	cd lib/vorbis/$(OS)/build/$(LIBOGG) && make clean && make
	cp -p lib/vorbis/$(OS)/build/$(LIBOGG)/src/.libs/libogg.a lib/vorbis/$(OS)/lib
	cp -p lib/vorbis/$(OS)/build/$(LIBOGG)/include/ogg/{ogg.h,os_types.h,config_types.h} lib/vorbis/$(OS)/include/ogg

lib/vorbis/$(OS)/lib/libvorbisidec.a: lib/vorbis/$(OS)/lib/libogg.a
	cd lib/vorbis/$(OS)/build && ${TAR} --bzip -xf ../../../../sources/$(LIBVORBIS).tar.bz2
	cd lib/vorbis/$(OS)/build && ${PATCH} -p0 -i ../../../../patches/$(LIBVORBIS)-version-script.patch
	cd lib/vorbis/$(OS)/build/$(LIBVORBIS) && $(SED) -i "s/-mno-ieee-fp//g" configure
	cd lib/vorbis/$(OS)/build/$(LIBVORBIS) && CC="$(CC)" CXXCPP="$(CPP)" OGG_CFLAGS=-I`pwd`/../../include OGG_LIBS="-L`pwd`/../../lib/libogg.a" CFLAGS="$(CFLAGS)" CPPFLAGS="$(CFLAGS)" LDFLAGS="$(LDFLAGS) -L`pwd`/../../lib ${OGG_LIBS}" ./configure --enable-shared=no --host=i686-pc-linux-gnu --build=mipsel-linux-uclibc --target=mipsel-linux-uclibc
	cd lib/vorbis/$(OS)/build/$(LIBVORBIS) && make clean && make
	cp -p lib/vorbis/$(OS)/build/$(LIBVORBIS)/.libs/libvorbisidec.a lib/vorbis/$(OS)/lib
	cp -p lib/vorbis/$(OS)/build/$(LIBVORBIS)/{ivorbiscodec.h,ivorbisfile.h,config_types.h} lib/vorbis/$(OS)/include/vorbis
	cd lib/vorbis/$(OS)/include/vorbis; ln -s ivorbisfile.h vorbisfile.h

lib/flac/$(OS)/lib/libFLAC.a: lib/vorbis/$(OS)/lib/libogg.a
	cd lib/flac/$(OS)/build && ${TAR} --bzip -xf ../../../../sources/$(LIBFLAC).tar.bz2
	cd lib/flac/$(OS)/build/$(LIBFLAC) && CC="$(CC)" CXXCPP="$(CPP)" OGG_CFLAGS=-I`pwd`/../../include OGG_LIBS=`pwd`/../../lib/libogg.a CFLAGS="$(CFLAGS)" CPPFLAGS="$(CFLAGS)" LDFLAGS="$(LDFLAGS) ${OGG_LIBS}" ./configure --enable-shared=no --disable-oggtest --disable-cpplibs --disable-xmms-plugin --with-ogg-libraries=`pwd`/../../../../vorbis/$(OS)/lib --with-ogg-includes=`pwd`/../../../../vorbis/$(OS)/include --host=i686-pc-linux-gnu --build=mipsel-linux --target=mipsel-linux
	cd lib/flac/$(OS)/build/$(LIBFLAC)/src/libFLAC && make clean && make
	cp -p lib/flac/$(OS)/build/$(LIBFLAC)/src/libFLAC/.libs/libFLAC.a lib/flac/$(OS)/lib
	cp -p lib/flac/$(OS)/build/$(LIBFLAC)/include/FLAC/{all.h,export.h,ordinals.h,assert.h,format.h,stream_decoder.h,callback.h,metadata.h,stream_encoder.h} lib/flac/$(OS)/include/FLAC

$(LIBPORTAUDIO): $(PORTAUDIOFILES:.c=.o)
	ar cru $(LIBPORTAUDIO) $^
	ranlib $(LIBPORTAUDIO)

$(LIBSLIMPROTO): $(SLIMPROTOFILES:.c=.o)
	ar cru $(LIBSLIMPROTO) $^
	ranlib $(LIBSLIMPROTO)

$(LIBGETOPT): $(GETOPTFILES:.c=.o)
	ar cru $(LIBGETOPT) $^
	ranlib $(LIBGETOPT)

$(SQUEEZESLAVE): $(SQUEEZESLAVEFILES:.c=.o) $(PORTMIXERFILES:.c=.o) $(LIBPORTAUDIO) $(LIBSLIMPROTO) $(LIBGETOPT) $(SUPPORTLIBS)
	$(CC) $(LDFLAGS) -static -o $(SQUEEZESLAVE) $^ -lpthread -lm
	mv $(SQUEEZESLAVE) $(SQUEEZESLAVE)-static
	$(CC) $(LDFLAGS) -o $(SQUEEZESLAVE) $^ -lpthread -lm -lgcc_s

clean:
	-@rm -f $(PORTAUDIOFILES:.c=.o)
	-@rm -f $(SLIMPROTOFILES:.c=.o)
	-@rm -f $(SQUEEZESLAVEFILES:.c=.o)
	-@rm -f $(PORTMIXERFILES:.c=.o)
	-@rm -f $(GETOPTFILES:.c=.o)
	-@rm -f $(LIBPORTAUDIO)
	-@rm -f $(LIBSLIMPROTO)
	-@rm -f $(LIBGETOPT)
	-@rm -f $(SQUEEZESLAVE) $(SQUEEZESLAVE)-static

realclean: clean
	-@rm -rf lib/libmad/$(OS)/build/$(LIBMAD)
	-@rm -rf lib/vorbis/$(OS)/build/$(LIBOGG)
	-@rm -rf lib/vorbis/$(OS)/build/$(LIBVORBIS)
	-@rm -rf lib/flac/$(OS)/build/$(LIBFLAC)
	-@rm -f lib/libmad/$(OS)/lib/libmad.a lib/libmad/$(OS)/include/mad.h
	-@rm -f lib/vorbis/$(OS)/lib/libogg.a lib/vorbis/$(OS)/include/ogg/{ogg.h,os_types.h,config_types.h}
	-@rm -f lib/vorbis/$(OS)/lib/libvorbisidec.a
	-@rm -f lib/vorbis/$(OS)/include/vorbis/{vorbisfile.h,ivorbiscodec.h,ivorbisfile.h,config_types.h}
	-@rm -f lib/flac/$(OS)/lib/libFLAC.a
	-@rm -f lib/flac/$(OS)/include/FLAC/{all.h,export.h,ordinals.h,assert.h,format.h,stream_decoder.h,callback.h,metadata.h,stream_encoder.h}

