CC=gcc
TAR=tar

CFLAGS=-Wall -DSLIMPROTO_DEBUG -DUSE_SIGNALS_FOR_RESTART -DPORTAUDIO_ALSA -g -m64

INCLUDE=-Ilib/libportaudio/linux26-amd64/include -Ilib/portmixer/px_common -Isrc

PORTMIXERFILES:=lib/portmixer/px_unix_oss/px_unix_oss.c

SLIMPROTOFILES:=src/slimaudio/slimaudio_http.c src/slimaudio/slimaudio_decoder.c src/slimaudio/slimaudio_decoder_flac.c src/slimaudio/slimaudio_decoder_mad.c src/slimaudio/slimaudio_decoder_vorbis.c src/slimaudio/slimaudio_decoder_pcm.c src/slimaudio/slimaudio_output.c src/slimaudio/slimaudio_buffer.c src/slimaudio/slimaudio.c src/slimproto/slimproto.c

SQUEEZESLAVEFILES:=src/squeezeslave/squeezeslave.c src/squeezeslave/help.c src/squeezeslave/daemonize.c src/squeezeslave/interactive.c

.c.o:
	${CC} $(CFLAGS) -c $(INCLUDE) $< -o $*.o

all : lib/libportaudio/linux26-amd64/lib/libportaudio.a bin/squeezeslave-amd64-alsa

# portaudio
portaudiov19/Makefile:
	cd lib/libportaudio/linux26-amd64/build && ${TAR} -xzf ../../../../sources/pa_snapshot-20090419.tar.gz
	cd lib/libportaudio/linux26-amd64/build/portaudio &&  CFLAGS="-m64" ./configure --without-jack --disable-shared

lib/libportaudio/linux26-amd64/lib/libportaudio.a: portaudiov19/Makefile
	cd lib/libportaudio/linux26-amd64/build/portaudio; make lib/libportaudio.la
	cp -p lib/libportaudio/linux26-amd64/build/portaudio/lib/.libs/libportaudio.a lib/libportaudio/linux26-amd64/lib
	cp -p lib/libportaudio/linux26-amd64/build/portaudio/include/portaudio.h lib/libportaudio/linux26-amd64/include

lib/libslimproto.a: $(SLIMPROTOFILES:.c=.o)
	ar cru lib/libslimproto.a $^
	ranlib lib/libslimproto.a

bin/squeezeslave-amd64-alsa : $(SQUEEZESLAVEFILES:.c=.o) $(PORTMIXERFILES:.c=.o) lib/libslimproto.a lib/libportaudio/linux26-amd64/lib/libportaudio.a
	${CC} -g -o bin/squeezeslave-amd64-alsa $^ /usr/lib/libmad.a /usr/lib/libFLAC.a /usr/lib/libvorbisfile.a /usr/lib/libvorbis.a /usr/lib/libogg.a -lasound -lrt -lpthread -lm

clean:
	@{ for FILE in $(PORTAUDIOFILES:.c=.o) \
	               $(SLIMPROTOFILES:.c=.o) \
	               $(PORTMIXERFILES:.c=.o) \
	               $(SQUEEZESLAVEFILES:.c=.o) \
	               lib/libslimproto.a \
	               bin/squeezeslave-amd64-alsa; do \
	  test -e $$FILE && echo $$FILE || true; \
	  test -e $$FILE && $(RM) $$FILE 2>/dev/null || true; \
	done; } | xargs --no-run-if-empty echo $(RM)
	-cd lib/libportaudio/linux26-amd64/build/portaudio && make distclean
