#!/bin/bash
VER=`svnversion`

make -f makefile.osx-intel-display realclean

make -f makefile.osx-ppc-display realclean
make -f makefile.osx-ppc-display
mv bin/squeezeslave bin/squeezeslave-ppc-0.9-$VER
make -f makefile.osx-ppc-display realclean

make -f makefile.osx-intel-display realclean
make -f makefile.osx-intel-display
mv bin/squeezeslave bin/squeezeslave-intel-0.9-$VER
