#!/bin/bash
VER=`svnversion`

if [ "`uname -r`" == "8.4.1" ]; then

    make -f makefile.osx-intel-display realclean

    make -f makefile.osx-ppc-display realclean
    make -f makefile.osx-ppc-display

    mv bin/squeezeslave bin/squeezeslave-ppc-0.9-$VER

    make -f makefile.osx-ppc-display realclean

    make -f makefile.osx-intel-display realclean
    make -f makefile.osx-intel-display

    mv bin/squeezeslave bin/squeezeslave-intel-0.9-$VER
fi

if [ "`uname -r`" == "10.4.1" ]; then

    make -f makefile.osx-intel-display realclean
    make -f makefile.osx-ppc-display realclean

    make -f makefile.osx-i64-display realclean
    make -f makefile.osx-i64-display

    mv bin/squeezeslave bin/squeezeslave-i64-0.9-$VER
fi
