#!/bin/bash
VER=`svnversion`

make -f makefile.linux24-i586-display realclean
make -f makefile.linux24-i586-display

gcc -static -o bin/squeezeslave src/squeezeslave/squeezeslave.o src/squeezeslave/help.o src/squeezeslave/daemonize.o src/squeezeslave/interactive.o lib/portmixer/px_unix_oss/px_unix_oss.o lib/libslimproto.a lib/libportaudio.a lib/vorbis/lnx24/lib/libvorbisidec.a /usr/lib/libmad.a /usr/lib/libFLAC.a lib/vorbis/lnx24/lib/libvorbisidec.a -lncurses -llirc_client /usr/lib/libogg.a -lpthread -lm

mv bin/squeezeslave bin/squeezeslave-mmx-display

make -f makefile.linux24-i586-display realclean

