#!/bin/bash

cd /cygdrive/h/source/squeezeslave
#VER=`svnversion`
VER=124

make -f makefile.mingw32-asio-display realclean
cd bin;tar -xf 7z.tar;cd ..
make -f makefile.mingw32-asio-display
mv bin/squeezeslave-asio.exe bin/squeezeslave-asio-0.9-$VER.exe
make -f makefile.mingw32-asio-display realclean

make -f makefile.mingw32-display realclean
cd bin;tar -xf 7z.tar;cd ..
make -f makefile.mingw32-display
mv bin/squeezeslave.exe bin/squeezeslave-0.9-$VER.exe

