#!/bin/bash
SQC="`dirname $0`/../src/squeezeslave/squeezeslave.c"
VER=`grep version\ = ${SQC} | awk -F\" '{print \$2}'`
REV=`svnversion`

make -f makefile.linux26-alsa-display realclean
make -f makefile.linux26-alsa-display

gcc -s -o bin/squeezeslave src/squeezeslave/squeezeslave.o src/squeezeslave/help.o src/squeezeslave/daemonize.o src/squeezeslave/interactive.o lib/portmixer/px_none/px_none.o lib/libslimproto.a lib/libgetopt.a lib/libportaudio/lnx26/lib/libportaudio.a lib/libmad/lnx26/lib/libmad.a lib/vorbis/lnx26/lib/libvorbisfile.a lib/vorbis/lnx26/lib/libvorbis.a lib/vorbis/lnx26/lib/libvorbisenc.a lib/vorbis/lnx26/lib/libogg.a lib/flac/lnx26/lib/libFLAC.a -lasound -lrt -lpthread -lm /usr/lib/libncurses.a /usr/lib/liblirc_client.a

mv bin/squeezeslave bin/squeezeslave-lnx26-$VER-$REV
make -f makefile.linux26-alsa-display realclean

