#!/bin/bash
usage() {
    echo >&2 "usage: $0 <svn revision number> <mod version>"
    exit 1
}

if [ -z $1 ]; then
    usage
fi

if [ -z $2 ]; then
    usage
fi

cd /var/tmp || exit 1

svn --quiet export -r$1 http://www.portaudio.com/repos/portaudio/trunk || exit 1

sed -i "s:^#define PA_VERSION_  1899:#define PA_VERSION_  $1$2:" trunk/src/common/pa_front.c || exit 1

cd trunk || exit 1

svn diff -r1543:1542 http://www.portaudio.com/repos/portaudio/trunk | patch -p0 || exit 1

# svn diff -r1603:1604 http://www.portaudio.com/repos/portaudio/trunk | patch -p0 || exit 1
patch -p0 << EOF
Index: Makefile.in
===================================================================
--- Makefile.in (revision 1596)
+++ Makefile.in (working copy)
@@ -56,6 +56,7 @@
	src/common/pa_process.o \\
	src/common/pa_skeleton.o \\
	src/common/pa_stream.o \\
+	src/common/pa_ringbuffer.o \\
	src/common/pa_trace.o

 TESTS = \\
_______________________________________________
EOF

if [ "$?" != "0" ]; then
    exit 1
fi

cd .. || exit 1
mv trunk portaudio || exit 1
tar -czf portaudio-r$1$2.tar.gz portaudio || exit 1
rm -rf portaudio

