#!/bin/bash
usage() {
    echo >&2 "usage: $0 <svn revision number>"
    exit 2
}

if [ -z $1 ]; then
    usage
fi

cd /var/tmp || exit 1

svn --quiet export -r$1 http://www.portaudio.com/repos/portaudio/trunk || exit 1

sed -i "s:^#define PA_VERSION_  1899:#define PA_VERSION_  $1:" trunk/src/common/pa_front.c || exit 1

cd trunk || exit 1

# svn diff -r1543:1542 http://www.portaudio.com/repos/portaudio/trunk | patch -p0 || exit 1

cd .. || exit 1
mv trunk portaudio || exit 1
tar -czf $HOME/source/squeezeslave/sources/portaudio-r$1.tar.gz portaudio || exit 1
rm -rf portaudio

